flowchart LR
A["A"]
B["B"]
C["C"]
A e1@--- B
A e2@--- C
classDef red-dash  stroke:#FF0000,stroke-width:3px,stroke-dasharray: 9,5
classDef green-solid stroke:#00aa00,stroke-width:3px;
class e1 red-dash
class e2 green-solid
